### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0ODAzMjg1LCJleHAiOjE2NjQ4ODk2ODV9.645WaMm6B8mufvmQrKoDHYe8RKLKDXWs3IBXUbOsjEE

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷"
}

### 상품 아이템 추가
POST http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k

{
  "productId": 1,
  "count": 1,
  "name": "유메가을옷(매우예쁨)",
  "price": 10000
}

### 상품 수정
PUT http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "한정판유메옷"
}

### 상품 아이템 수정
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k

{
  "id": 1,
  "count": 1,
  "name": "유메가을옷(매우예쁨)",
  "price": 10000
}

### 상품 삭제
DELETE http://localhost:8081/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "한정판유메옷"
}

### 상품 아이템 삭제
DELETE http://localhost:8081/seller/product/item?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k


### 상품 검색
GET http://localhost:8081/search/product?name=유메
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8081/search/product/detail?productId=1
Content-Type: application/json

### 카트 추가
POST http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ3MjUyMDAsImV4cCI6MTY2NDgxMTYwMH0.kUeSvJr27WCEG2QSUiSVQOU-ATeekg6JeDpvHOkEb1s

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷",
  "sellerId": 1
}

### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0NzI0OTgzLCJleHAiOjE2NjQ4MTEzODN9.Aq6Q9JEKzMAJYBoLwj2_DilRnvY_vWziiGsnlddz5-k

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷"
}

### 카트 조회
GET http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ3MjUyMDAsImV4cCI6MTY2NDgxMTYwMH0.kUeSvJr27WCEG2QSUiSVQOU-ATeekg6JeDpvHOkEb1s

### 카트 주문
POST http://localhost:8081/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ3MjUyMDAsImV4cCI6MTY2NDgxMTYwMH0.kUeSvJr27WCEG2QSUiSVQOU-ATeekg6JeDpvHOkEb1s


{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "sellerId": 1,
      "name": "유메옷",
      "description": "상품 설명",
      "items": [
        {
          "id": 1,
          "name": "유메가을옷",
          "count": 1,
          "price": 1000000
        }
      ]
    }
  ],
  "messages": []
}