### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

{
  "description": "귀여운 유메의 가을 신상입니다",
  "items": [
    {
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷"
}

### 상품 아이템 추가
POST http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

{
  "productId": 1,
  "count": 1,
  "name": "유메가을옷(매우예쁨)",
  "price": 10000
}

### 상품 수정
PUT http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

{
  "description": "귀여운 유메의 가을 신상입니다",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "유메가을옷",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "한정판유메옷"
}

### 상품 아이템 수정
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0ODg0NzIxLCJleHAiOjE2NjQ5NzExMjF9.O347VCJdDBpvlOaQ_E2uLN7AxakJQu1-gTOCc8Apqmg

{
  "id": 1,
  "count": 5,
  "name": "유메가을옷(따뜻한재질)",
  "price": 10000
}

### 상품 삭제
DELETE http://localhost:8081/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0ODg0NzIxLCJleHAiOjE2NjQ5NzExMjF9.O347VCJdDBpvlOaQ_E2uLN7AxakJQu1-gTOCc8Apqmg

{
  "description": "귀여운 유메의 가을 신상입니다",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "id": 1,
  "name": "한정판유메옷"
}

### 상품 아이템 삭제
DELETE http://localhost:8081/seller/product/item?id=3
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0ODg0NzIxLCJleHAiOjE2NjQ5NzExMjF9.O347VCJdDBpvlOaQ_E2uLN7AxakJQu1-gTOCc8Apqmg


### 상품 검색
GET http://localhost:8081/search/product?name=유메
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8081/search/product/detail?productId=1
Content-Type: application/json

### 카트 추가
POST http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

{
  "description": "귀여운 유메의 가을 신상입니다",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷",
  "sellerId": 1
}

### 상품 추가
POST http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY0ODg0NzIxLCJleHAiOjE2NjQ5NzExMjF9.O347VCJdDBpvlOaQ_E2uLN7AxakJQu1-gTOCc8Apqmg

{
  "description": "귀여운 유메의 가을 신상입니다",
  "items": [
    {
      "count": 1,
      "name": "유메가을옷",
      "price": 10000
    }
  ],
  "name": "유메옷"
}

### 카트 조회
GET http://localhost:8081/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

### 카트 주문
POST http://localhost:8081/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1MjE0MzUyLCJleHAiOjE2NjUzMDA3NTJ9.3ROPEzSugB9AtUyP65-XqewP7xCma1BMak0X_kHg7G4

{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "sellerId": 1,
      "name": "유메옷",
      "description": "귀여운 유메의 가을 신상입니다",
      "items": [
        {
          "id": 1,
          "name": "유메가을옷",
          "count": 1,
          "price": 100000
        }
      ]
    }
  ],
  "messages": []
}

