### 회원가입 (고객)
POST http://localhost:8080/signup/customer
Content-Type: application/json

{
  "birth": "1991-01-14",
  "email": "amyyzzin@naver.com",
  "name": "string",
  "password": "AMYYzzin@123",
  "phone": "0109228-0921"
}


### 이메일 인증 (고객)
GET http://localhost:8080/signup/customer/verify/?email=amyyzzin@naver.com&code=BoWxVBLXOV


### 로그인(고객)
POST http://localhost:8080/signIn/customer
Content-Type: application/json

{
  "email": "amyyzzin@naver.com",
  "password": "string"
}


### 회원 정보 조회(고객)
GET http://localhost:8080/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ5MzkzMjMsImV4cCI6MTY2NTAyNTcyM30.cFidNEggk1wUfZYZ2MVCNxsEvMpAniO0JMatQexuilw


### 잔액 변경 (고객)
POST http://localhost:8080/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtTFc4Q25jazFUSXFwYXNTOHd1a1ZRSW5jOXdrcGdEM2FnSWRCR0NFa3pzPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NjQ5MzkzMjMsImV4cCI6MTY2NTAyNTcyM30.cFidNEggk1wUfZYZ2MVCNxsEvMpAniO0JMatQexuilw

{
  "from": "amyyzzin@naver.com",
  "message": "용돈",
  "money": 100000
}



### 회원가입(셀러)
POST http://localhost:8080/signup/seller
Content-Type: application/json

{
  "birth": "1991-01-14",
  "email": "amyyzzin@naver.com",
  "name": "string",
  "password": "string",
  "phone": "010-0000-0000"
}

### 이메일 인증 (셀러)
GET http://localhost:8080/signup/seller/verify/?email=amyyzzin@naver.com&code=7E25YIpdrD

### 로그인(셀러)
POST http://localhost:8080/signIn/seller
Content-Type: application/json

{
  "email": "amyyzzin@naver.com",
  "password": "string"
}
